language: python

python:
 - "3.6"

cache: pip

install:
 - pip install -r requirements.txt
 - pip install nose
 - pip install coverage

script:
 - nosetests -v test --with-coverage --cover-package=lace --cover-html
