language: python

python:
 - "3.6"

cache: pip

install:
 - pip install -r requirements.txt
 - pip install nose coverage coveralls

script:
 nosetests -v test --with-coverage --cover-package=shoelace

after_success:
  coveralls
